/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HackRouteImport } from './routes/hack'
import { Route as ServeRouteImport } from './routes/serve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HackRoute = HackRouteImport.update({
  id: '/hack',
  path: '/hack',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeRoute = ServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/hack': typeof HackRoute
  '/serve': typeof ServeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/hack': typeof HackRoute
  '/serve': typeof ServeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/hack': typeof HackRoute
  '/serve': typeof ServeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events' | '/hack' | '/serve'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/hack' | '/serve'
  id: '__root__' | '/' | '/events' | '/hack' | '/serve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  HackRoute: typeof HackRoute
  ServeRoute: typeof ServeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hack': {
      id: '/hack'
      path: '/hack'
      fullPath: '/hack'
      preLoaderRoute: typeof HackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve': {
      id: '/serve'
      path: '/serve'
      fullPath: '/serve'
      preLoaderRoute: typeof ServeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  HackRoute: HackRoute,
  ServeRoute: ServeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
